### ISSUE TITLE
Avoid scheduled workflows becoming disabled due to lack of repo activity

### ISSUE THREAD

**Issue by matthewfeickert** [scientific-python/upload-nightly-action#17]
> I didn't realize inactive repos have their actions switched off. What do we need to do; a monthly empty commit?

_Originally posted by @stefanv in https://github.com/scientific-python/upload-nightly-action/issues/12#issuecomment-1584931283_

**Comment by matthewfeickert** [comment]
Capturing https://github.com/scientific-python/upload-nightly-action/pull/12#issuecomment-1585084443

> One commit every 50 days on a `keepalive` branch isn't too bad :)
> 
> https://github.com/marketplace/actions/keepalive-workflow
> - @stefanv 

and https://github.com/scientific-python/upload-nightly-action/pull/12#issuecomment-1585087224

> Ahh, nice, thanks for the link. I was starting to hack something together, but it's probably much easier to just do the action. I'll open a PR for this.
> - @bsipocz 

I had seen that but didn't directly recommend as I didn't know from a first glance if it allowed configuration of which branch to push to. I believe there are other solutions out there already on the [GitHub Actions marketplace](https://github.com/marketplace?type=actions), so probably worth poking around and finding out what exits.

**Comment by matthewfeickert** [comment]
What I described in https://github.com/scientific-python/upload-nightly-action/pull/12#issuecomment-1584981888 could also be done by us also by having a workflow that is similar to https://github.com/iris-hep/analysis-community-summary/blob/main/.github/workflows/deploy.yml that includes something like (probably needs some tweaking of parameters)

```yaml
...
    - name: Keep workflow alive
      if: success() && github.event_name == 'schedule'
      uses: peaceiris/actions-gh-pages@v3  # major version probably not a security concern here as no deploy
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: keep-alive
        publish_dir: something
        enable_jekyll: true  # avoid extra files
        force_orphan: true  # overwirte
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: Keep repo GitHub Actions alive
```
