### ISSUE TITLE
Consider not advocating using action from `main`

### ISSUE THREAD

**Issue by matthewfeickert** [scientific-python/upload-nightly-action#7]
At the moment the `v0.1.0` docs advocate that users use the action from `main` and not from a specific tag.

https://github.com/scientific-python/upload-nightly-action/blob/80af44feb2d73fe29869d46207c02f88885ea5b8/README.md?plain=1#L10-L17

This seems like a security issue that should be avoided and that @webknjaz has discussed before for https://github.com/pypa/gh-action-pypi-publish.

A more secure option is to advocate that users use release tags and dependabot to check for updates to the GitHub Actions that they use and then consider from the PR if the update in the tag is something they are ready to accept. Example `.github/dependabot.yml` (taken from [Scikit-HEP developer recommendations](https://scikit-hep.org/developer/gha_basic#updating) (thanks @henryiii!)):

```yaml
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```
